In [5]:
import pickle
import numpy as np
import torch

In [9]:
with open('outputs/FMNIST/resnet18.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res

for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

# print(cover_accs)
# print(avg_counts)

print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_counts, 1)))
print(np.std(np.average(avg_counts, 1)))

# print(np.mean(np.average(np.delete(cover_accs, 7, axis=0), 1)))
# print(np.std(np.average(np.delete(cover_accs, 7, axis=0), 1)))

# print(np.mean(np.average(np.delete(avg_counts, 7, axis=0), 1)))
# print(np.std(np.average(np.delete(avg_counts, 7, axis=0), 1)))

0.95386666
0.0021458012
0.9539223
0.0021647627


In [13]:
with open('outputs/FMNIST/resnet34.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res

for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

# print(cover_accs)
# print(avg_counts)

print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_counts, 1)))
print(np.std(np.average(avg_counts, 1)))

0.95761997
0.001739455
0.96021
0.00568728


In [18]:
with open('outputs/FMNIST/vgg16.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res

for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

# print(cover_accs)
# print(avg_counts)

# print(np.mean(np.average(cover_accs, 1)))
# print(np.std(np.average(cover_accs, 1)))

# print(np.mean(np.average(avg_counts, 1)))
# print(np.std(np.average(avg_counts, 1)))

print(np.mean(np.average(np.delete(cover_accs, 1, axis=0), 1)))
print(np.std(np.average(np.delete(cover_accs, 1, axis=0), 1)))

print(np.mean(np.average(np.delete(avg_counts, 1, axis=0), 1)))
print(np.std(np.average(np.delete(avg_counts, 1, axis=0), 1)))

0.95215565
0.0029608794
0.9548667
0.0019561625


In [21]:
benchmark = np.array([1] * 9 + [0])
weights5 = [1000] * 9 + [int(9000 / 19)]
weights10 = [1000] * 9 + [int(9000 / 9)]

In [22]:
with open('outputs/FMNIST/resnet18_outlier.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res

for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

print(cover_accs)
print(avg_counts)

print(np.mean(np.average(cover_accs, 1, weights = weights5)))
print(np.std(np.average(cover_accs, 1, weights = weights5)))

print(np.mean(np.average(avg_counts - benchmark, 1, weights = weights5)))
print(np.std(np.average(avg_counts - benchmark, 1, weights = weights5)))

[[0.961 0.955 0.959 0.95  0.951 0.946 0.956 0.955 0.966 0.374]
 [0.947 0.961 0.959 0.95  0.961 0.936 0.95  0.956 0.949 0.   ]
 [0.944 0.955 0.956 0.959 0.953 0.953 0.952 0.966 0.953 0.712]
 [0.953 0.962 0.962 0.956 0.952 0.963 0.944 0.962 0.961 0.09 ]
 [0.951 0.963 0.959 0.956 0.945 0.959 0.954 0.963 0.955 0.   ]
 [0.946 0.957 0.954 0.961 0.953 0.947 0.952 0.955 0.954 0.149]
 [0.957 0.941 0.962 0.959 0.954 0.96  0.953 0.958 0.955 0.514]
 [0.955 0.955 0.97  0.933 0.968 0.957 0.956 0.957 0.96  0.636]
 [0.959 0.963 0.975 0.958 0.968 0.956 0.951 0.961 0.951 0.417]
 [0.951 0.954 0.947 0.958 0.955 0.95  0.94  0.961 0.959 0.392]]
[[0.961 0.955 0.959 0.95  0.951 0.946 0.956 0.955 0.966 0.626]
 [1.945 1.961 1.951 1.95  1.959 1.936 0.95  1.959 1.949 1.777]
 [0.944 0.955 0.956 0.959 0.954 0.953 0.952 0.966 0.953 0.288]
 [0.953 0.962 0.962 0.956 0.957 0.963 0.944 0.962 0.961 0.91 ]
 [1.95  1.963 1.951 1.956 1.94  1.959 0.954 1.963 1.955 1.888]
 [0.946 0.957 0.954 0.961 0.953 0.947 0.952 0.955 0.95

In [3]:
# naive and APS
with open('../APS/APS_Res18_fmnist.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

# print(np.std(np.mean(top1s_acc, 1)))
# print(np.std(np.mean(top3s_acc, 1)))

print(np.mean(np.mean(naive_covers, 1)))
print(np.std(np.mean(naive_covers, 1)))

print(np.mean(np.mean(APS_covers, 1)))
print(np.std(np.mean(APS_covers, 1)))

print(np.mean(np.mean(naive_sizes, 1)))
print(np.std(np.mean(naive_sizes, 1)))

print(np.mean(np.mean(APS_sizes, 1)))
print(np.std(np.mean(APS_sizes, 1)))

0.8959600000000002
0.0020105720578979178
0.9456
0.0014966629547094991
1.0768
0.007523828812512998
1.22418
0.01227866442248505


In [7]:
# naive and APS
with open('../APS/APS_Res34_fmnist.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

# print(np.std(np.mean(top1s_acc, 1)))
# print(np.std(np.mean(top3s_acc, 1)))

print(np.mean(np.mean(naive_covers, 1)))
print(np.std(np.mean(naive_covers, 1)))

print(np.mean(np.mean(APS_covers, 1)))
print(np.std(np.mean(APS_covers, 1)))

print(np.mean(np.mean(naive_sizes, 1)))
print(np.std(np.mean(naive_sizes, 1)))

print(np.mean(np.mean(APS_sizes, 1)))
print(np.std(np.mean(APS_sizes, 1)))

0.89284
0.0016548111674751116
0.94618
0.0017302023003106428
1.04436
0.003965148168732161
1.18532
0.0174980456051527


In [3]:
# naive and APS
with open('../APS/APS_VGG16_fmnist.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

# print(np.std(np.mean(top1s_acc, 1)))
# print(np.std(np.mean(top3s_acc, 1)))

print(np.mean(np.mean(naive_covers, 1)))
print(np.std(np.mean(naive_covers, 1)))

print(np.mean(np.mean(APS_covers, 1)))
print(np.std(np.mean(APS_covers, 1)))

print(np.mean(np.mean(naive_sizes, 1)))
print(np.std(np.mean(naive_sizes, 1)))

print(np.mean(np.mean(APS_sizes, 1)))
print(np.std(np.mean(APS_sizes, 1)))

0.8973800000000001
0.00274401166178282
0.94668
0.002768681996907537
1.00446
0.003280304863880807
1.10814
0.014224148480664897


In [22]:
# naive and APS
with open('../APS/APS_VGG16_fmnist_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights5)))
print(np.std(np.average(naive_covers, 1, weights = weights5)))

print(np.mean(np.average(APS_covers, 1, weights = weights5)))
print(np.std(np.average(APS_covers, 1, weights = weights5)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights5)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights5)))

0.8477620605932652
0.010727903243785001
0.8975984376649425
0.0027443330668506225
0.1151831098912699
0.07923778976548995
0.3157968806080439
0.05287895030521173


In [37]:
# naive and APS
with open('../APS/APS_VGG16_fmnist_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

## delete an outlier
naive_covers = [x for i,x in enumerate(naive_covers) if i!=5]
APS_covers = [x for i,x in enumerate(APS_covers) if i!=5]
naive_sizes = [x for i,x in enumerate(naive_sizes) if i!=5]
APS_sizes = [x for i,x in enumerate(APS_sizes) if i!=5]

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights10)))
print(np.std(np.average(naive_covers, 1, weights = weights10)))

print(np.mean(np.average(APS_covers, 1, weights = weights10)))
print(np.std(np.average(APS_covers, 1, weights = weights10)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights10)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights10)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights10)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights10)))

0.8003263157894738
0.004904009326991984
0.8510526315789475
0.0019470269970967972
0.21828421052631575
0.03191424798388223
0.49041052631578946
0.05367881964676906


In [38]:
# naive and APS
with open('../APS/APS_Res18_fmnist_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights5)))
print(np.std(np.average(naive_covers, 1, weights = weights5)))

print(np.mean(np.average(APS_covers, 1, weights = weights5)))
print(np.std(np.average(APS_covers, 1, weights = weights5)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights5)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights5)))

0.8426528027024173
0.0035431310569854577
0.8985379499630527
0.0015152177842638666
0.136705315106091
0.007703175554899455
0.3743107885569513
0.014074595724119893


In [41]:
# naive and APS
with open('../APS/APS_Res18_fmnist_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights10)))
print(np.std(np.average(naive_covers, 1, weights = weights10)))

print(np.mean(np.average(APS_covers, 1, weights = weights10)))
print(np.std(np.average(APS_covers, 1, weights = weights10)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights10)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights10)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights10)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights10)))

0.796415
0.0023113361936334584
0.85099
0.001372552366942691
0.33125499999999997
0.015121027577516018
0.6894899999999999
0.026707319221516795


In [42]:
# naive and APS
with open('../APS/APS_Res34_fmnist_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights5)))
print(np.std(np.average(naive_covers, 1, weights = weights5)))

print(np.mean(np.average(APS_covers, 1, weights = weights5)))
print(np.std(np.average(APS_covers, 1, weights = weights5)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights5)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights5)))

0.8288504169745593
0.0032540353083972485
0.8993032830148844
0.0016302250022308137
0.10322761532777365
0.021591097225197694
0.39447961575002644
0.036293440976599346


In [43]:
# naive and APS
with open('../APS/APS_Res34_fmnist_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights10)))
print(np.std(np.average(naive_covers, 1, weights = weights10)))

print(np.mean(np.average(APS_covers, 1, weights = weights10)))
print(np.std(np.average(APS_covers, 1, weights = weights10)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights10)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights10)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights10)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights10)))

0.78497
0.0024702429030360497
0.85108
0.00197119253245339
0.22773000000000004
0.012855586334352862
0.6167800000000001
0.030486449448894518


In [18]:
# FCI on VGG16
with open('fmnist/FCI_VGG16_fmnist.pkl', 'rb') as inp:
    res = pickle.load(inp)
top1s, top3s, cover_accs, avg_counts = res
for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

print(np.mean(np.mean(cover_accs, 1)))
print(np.std(np.mean(cover_accs, 1)))

print(np.mean(np.mean(avg_counts, 1)))
print(np.std(np.mean(avg_counts, 1)))

0.93887997
0.0018082102
0.93887997
0.0018082102


In [21]:
with open('fmnist/FCI_VGG16_fmnist_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res

for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

print(np.mean(np.average(cover_accs, 1, weights = weights5)))
print(np.std(np.average(cover_accs, 1, weights = weights5)))

print(np.mean(np.average(avg_counts, 1, weights = weights5)))
print(np.std(np.average(avg_counts, 1, weights = weights5)))

0.9578714445779181
0.001813124912862376
0.042128554740917715
0.001813128275162122


In [22]:
with open('fmnist/FCI_VGG16_fmnist_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res

for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

print(np.mean(np.average(cover_accs, 1, weights = weights10)))
print(np.std(np.average(cover_accs, 1, weights = weights10)))

print(np.mean(np.average(avg_counts, 1, weights = weights10)))
print(np.std(np.average(avg_counts, 1, weights = weights10)))

0.9577200031280517
0.0020989504153993547
0.04228000040864572
0.0020989520765093746


In [5]:
# FCI on Res18
with open('fmnist/FPI_resnet18_fmnist_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res
for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.mean(cover_accs, 1)))
print(np.std(np.mean(cover_accs, 1)))

print(np.mean(np.mean(avg_errors, 1)))
print(np.std(np.mean(avg_errors, 1)))

0.99969995
0.00018973673
0.23379
0.030671332


In [11]:
# FCI on Res18 with outliers

with open('fmnist/FCI_Res18_fmnist_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res
for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

print(np.mean(np.average(cover_accs, 1, weights = weights5)))
print(np.std(np.average(cover_accs, 1, weights = weights5)))

print(np.mean(np.average(avg_counts, 1, weights = weights5)))
print(np.std(np.average(avg_counts, 1, weights = weights5)))

0.94701750378978
0.0027702445679946173
0.052982493938484664
0.002770249265421771


In [12]:
# FCI on Res18 with outliers

with open('fmnist/FCI_Res18_fmnist_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res
for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(cover_accs, 1, weights = weights10)))
print(np.std(np.average(cover_accs, 1, weights = weights10)))

print(np.mean(np.average(avg_counts, 1, weights = weights10)))
print(np.std(np.average(avg_counts, 1, weights = weights10)))

0.9473499993483226
0.008730165656534304
0.05265000021511999
0.008730167922643374


In [13]:
# FCI on Res34
with open('fmnist/FCI_Res34_fmnist.pkl', 'rb') as inp:
    res = pickle.load(inp)
top1s, top3s, cover_accs, avg_counts = res
for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

print(np.mean(np.mean(cover_accs, 1)))
print(np.std(np.mean(cover_accs, 1)))

print(np.mean(np.mean(avg_counts, 1)))
print(np.std(np.mean(avg_counts, 1)))

0.95056
0.0024743355
9.95056
0.0024743322


In [16]:
# FCI on Res34 with outliers
with open('fmnist/FCI_Res34_fmnist_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res
for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(cover_accs, 1, weights = weights5)))
print(np.std(np.average(cover_accs, 1, weights = weights5)))

print(np.mean(np.average(avg_counts, 1, weights = weights5)))
print(np.std(np.average(avg_counts, 1, weights = weights5)))

0.9641296290475465
0.0036411776626115123
0.03587036841105291
0.0036411801951418904


In [17]:
with open('fmnist/FCI_Res34_fmnist_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_counts = res

for i in range(len(avg_counts)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_counts[i] = avg_counts[i].numpy()
cover_accs = np.array(cover_accs)
avg_counts = np.array(avg_counts)

print(np.mean(np.average(cover_accs, 1, weights = weights10)))
print(np.std(np.average(cover_accs, 1, weights = weights10)))

print(np.mean(np.average(avg_counts, 1, weights = weights10)))
print(np.std(np.average(avg_counts, 1, weights = weights10)))

0.9580599999427795
0.010956204077373433
0.04194000029936432
0.010956203929771351
