In [3]:
import pickle
import numpy as np
import torch

benchmark = np.array([1] * 7 + [0] + [1] * 2)
weights5 = [1000] * 7 + [int(9000 / 19)] + [1000] * 2

In [58]:
# naive and APS
with open('../APS/APS_resnet18_cifar10_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

# print(np.std(np.mean(top1s_acc, 1)))
# print(np.std(np.mean(top3s_acc, 1)))

print(np.mean(np.mean(naive_covers, 1)))
print(np.std(np.mean(naive_covers, 1)))

print(np.mean(np.mean(APS_covers, 1)))
print(np.std(np.mean(APS_covers, 1)))

print(np.mean(np.mean(naive_sizes, 1)))
print(np.std(np.mean(naive_sizes, 1)))

print(np.mean(np.mean(APS_sizes, 1)))
print(np.std(np.mean(APS_sizes, 1)))

0.9044699999999999
0.0021753390540327692
0.9490400000000001
0.0029584455377782612
1.8813900000000001
0.014122708663708983
2.3847200000000006
0.047641532301133986


In [4]:
# naive and APS
with open('../APS/APS_resnet34_cifar10_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

# print(np.std(np.mean(top1s_acc, 1)))
# print(np.std(np.mean(top3s_acc, 1)))

print(np.mean(np.mean(naive_covers, 1)))
print(np.std(np.mean(naive_covers, 1)))

print(np.mean(np.mean(APS_covers, 1)))
print(np.std(np.mean(APS_covers, 1)))

print(np.mean(np.mean(naive_sizes, 1)))
print(np.std(np.mean(naive_sizes, 1)))

print(np.mean(np.mean(APS_sizes, 1)))
print(np.std(np.mean(APS_sizes, 1)))

0.9103200000000001
0.004147963355672301
0.9502499999999999
0.0015564382416273386
1.9636100000000003
0.02466700022296997
2.4343600000000003
0.040347346876839295


In [12]:
# naive and APS
with open('../APS/APS_vgg16_cifar10_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

# print(np.std(np.mean(top1s_acc, 1)))
# print(np.std(np.mean(top3s_acc, 1)))

print(np.mean(np.mean(naive_covers, 1)))
print(np.std(np.mean(naive_covers, 1)))

print(np.mean(np.mean(APS_covers, 1)))
print(np.std(np.mean(APS_covers, 1)))

print(np.mean(np.mean(naive_sizes, 1)))
print(np.std(np.mean(naive_sizes, 1)))

print(np.mean(np.mean(APS_sizes, 1)))
print(np.std(np.mean(APS_sizes, 1)))

0.9027100000000001
0.0049964887671243565
0.94825
0.0027569004334578053
1.43045
0.044016457149570816
1.7686199999999999
0.054878480299658444


In [27]:
benchmark = np.array([1] * 7 + [0] + [1] * 2)
weights5 = [1000] * 7 + [int(9000 / 19)] + [1000] * 2

In [28]:
# naive and APS
with open('../APS/APS_vgg16_cifar10_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights5)))
print(np.std(np.average(naive_covers, 1, weights = weights5)))

print(np.mean(np.average(APS_covers, 1, weights = weights5)))
print(np.std(np.average(APS_covers, 1, weights = weights5)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights5)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights5)))

0.8588831415602238
0.004517265421451552
0.8999366620922622
0.002323565242949218
0.49001372321334313
0.04059725614610346
0.7950279742425841
0.06002402685008042


In [29]:
# naive and APS
with open('../APS/APS_vgg16_cifar10_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1)))
print(np.std(np.average(naive_covers, 1)))

print(np.mean(np.average(APS_covers, 1)))
print(np.std(np.average(APS_covers, 1)))

print(np.mean(np.average(naive_sizes - benchmark, 1)))
print(np.std(np.average(naive_sizes - benchmark, 1)))

print(np.mean(np.average(APS_sizes - benchmark, 1)))
print(np.std(np.average(APS_sizes - benchmark, 1)))

0.8177999999999999
0.00508251906046591
0.85185
0.003591448175875586
0.60962
0.046853469455313594
0.9086799999999998
0.03239780239460695


In [30]:
# naive and APS
with open('../APS/APS_resnet18_cifar10_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights5)))
print(np.std(np.average(naive_covers, 1, weights = weights5)))

print(np.mean(np.average(APS_covers, 1, weights = weights5)))
print(np.std(np.average(APS_covers, 1, weights = weights5)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights5)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights5)))

0.8610260741053521
0.0026885472530812963
0.9031563390689328
0.002865102156222922
0.8856117386255674
0.020960509673344865
1.3561912804813683
0.015399261969592544


In [31]:
# naive and APS
with open('../APS/APS_resnet18_cifar10_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1)))
print(np.std(np.average(naive_covers, 1)))

print(np.mean(np.average(APS_covers, 1)))
print(np.std(np.average(APS_covers, 1)))

print(np.mean(np.average(naive_sizes - benchmark, 1)))
print(np.std(np.average(naive_sizes - benchmark, 1)))

print(np.mean(np.average(APS_sizes - benchmark, 1)))
print(np.std(np.average(APS_sizes - benchmark, 1)))

0.81132
0.0014012851244482665
0.8532500000000001
0.00230965365368923
0.97011
0.014688461457892694
1.4481000000000002
0.04004474996800461


In [18]:
benchmark

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [32]:
# naive and APS
with open('../APS/APS_resnet34_cifar10_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1, weights = weights5)))
print(np.std(np.average(naive_covers, 1, weights = weights5)))

print(np.mean(np.average(APS_covers, 1, weights = weights5)))
print(np.std(np.average(APS_covers, 1, weights = weights5)))

print(np.mean(np.average(naive_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(naive_sizes - benchmark, 1, weights = weights5)))

print(np.mean(np.average(APS_sizes - benchmark, 1, weights = weights5)))
print(np.std(np.average(APS_sizes - benchmark, 1, weights = weights5)))

0.8685105035363666
0.0022779154644683524
0.9032196769766705
0.0022471819961829196
0.9909004539216723
0.0219518524028237
1.4113902670748444
0.04720453132891177


In [33]:
# naive and APS
with open('../APS/APS_resnet34_cifar10_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
naive_covert, naive_sizet, APS_covert, APS_sizet, top1t_acc, top3t_acc, \
naive_covers, naive_sizes, APS_covers, APS_sizes, top1s_acc, top3s_acc = res

# print(np.mean(np.mean(top1s_acc, 1)))
# print(np.mean(np.mean(top3s_acc, 1)))

print(np.mean(np.average(naive_covers, 1)))
print(np.std(np.average(naive_covers, 1)))

print(np.mean(np.average(APS_covers, 1)))
print(np.std(np.average(APS_covers, 1)))

print(np.mean(np.average(naive_sizes - benchmark, 1)))
print(np.std(np.average(naive_sizes - benchmark, 1)))

print(np.mean(np.average(APS_sizes - benchmark, 1)))
print(np.std(np.average(APS_sizes - benchmark, 1)))

0.8169299999999999
0.0029342971901291817
0.8527799999999999
0.0033869750515762376
1.0814500000000002
0.028048859156835665
1.51488
0.026742916819225235


In [4]:
with open('cifar10/FCI_resnet18_cifar10_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))


0.97290003
0.013783355
0.58685
0.27786976


In [4]:
with open('cifar10/FPI_resnet18_cifar10_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.99660003
0.005525573
0.2806
0.29817313


In [5]:
with open('cifar10/FCI_resnet34_cifar10_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.9566
0.031131074
1.0947502
0.36576214


In [20]:
with open('cifar10/FCI_Res34_cifar10_OOD.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.91779995
0.008299977
0.08770001
0.013800006


In [67]:
print(cover_accs)
print(avg_errors)

[[0.939 0.873 0.922 0.999 0.955 0.907 0.965 0.944 0.947 0.935]
 [0.999 0.95  0.967 0.958 0.894 0.845 0.991 0.95  0.807 0.876]
 [0.986 0.855 0.906 0.989 0.897 0.898 0.974 0.907 0.944 0.862]
 [0.999 0.954 0.924 0.947 0.937 0.854 0.969 0.977 0.949 0.957]]
[[1.799 1.63  2.744 3.161 3.388 3.436 4.104 1.446 1.633 1.698]
 [1.372 1.234 2.079 2.448 2.468 3.153 2.115 1.372 1.244 2.146]
 [1.501 1.257 1.945 2.534 2.564 2.456 3.155 1.871 1.188 1.193]
 [1.327 0.994 2.07  2.68  2.294 2.628 2.461 1.708 1.131 0.99 ]]


In [23]:
with open('cifar10/FCI_vgg16_cifar10_OOD0.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.95133334
0.0007717407
6.2791333
0.31130558


In [7]:
FCI_weights5 = [1000] * 9 + [int(9000 / 19)] 

In [8]:
with open('cifar10/FCI_resnet18_cifar10_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.average(cover_accs, 1, weights = FCI_weights5)))
print(np.std(np.average(cover_accs, 1, weights = FCI_weights5)))

print(np.mean(np.average(avg_errors, 1, weights = FCI_weights5)))
print(np.std(np.average(avg_errors, 1, weights = FCI_weights5)))

0.9467763764308493
0.026332330134995408
0.32185080811451217
0.2901682196321764


In [14]:
np.average(np.array([1.0000, 1.0000, 1.0000, 0.9940, 0.9980, 1.0000, 0.9940, 0.9870, 0.8480,
        0.1180]))

0.8939

In [15]:
np.average(np.array([0.6350, 0.8710, 1.7410, 1.1860, 1.7270, 2.2370, 1.9060, 0.3430, 0.4980,
        2.4530]))

1.3597

In [9]:
with open('cifar10/FCI_resnet34_cifar10_OOD5.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

print(np.mean(np.average(cover_accs[[0, 2]], 1, weights = FCI_weights5)))
print(np.std(np.average(cover_accs[[0, 2]], 1, weights = FCI_weights5)))

print(np.mean(np.average(avg_errors[[0, 2]], 1, weights = FCI_weights5)))
print(np.std(np.average(avg_errors[[0, 2]], 1, weights = FCI_weights5)))

0.9475368975296854
0.0034958337901902503
0.6780235385774911
0.4179724461525744


In [15]:
avg_counts

array([[2.837, 1.859, 2.006, 2.81 , 1.934, 3.354, 2.064, 1.866, 1.868,
        3.674],
       [3.36 , 3.539, 2.614, 3.596, 2.485, 4.051, 2.418, 3.416, 3.926,
        4.514],
       [1.212, 0.991, 2.009, 3.262, 2.186, 3.147, 0.894, 1.03 , 1.168,
        3.621]], dtype=float32)

In [4]:
with open('cifar10/FCI_Res18_cifar10_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

## treat as OOD10
print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.90395
0.013546492
0.09985001
0.01769315


In [10]:
with open('cifar10/FCI_resnet18_cifar10_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

## treat as OOD10
print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.89164
0.040097795
0.69684994
0.427398


In [11]:
with open('cifar10/FCI_resnet34_cifar10_OOD10.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

## treat as OOD10
print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.89537
0.023139918
1.2998599
0.5702601


In [20]:
cover_accs

array([[0.991, 0.999, 1.   , 0.953, 0.996, 0.988, 0.965, 0.989, 0.875,
        0.   ],
       [1.   , 0.998, 0.999, 0.94 , 0.996, 0.993, 0.969, 0.986, 0.987,
        0.   ],
       [0.993, 0.989, 0.992, 0.994, 1.   , 0.946, 0.971, 0.988, 0.986,
        0.   ]], dtype=float32)

In [5]:
with open('cifar10/FCI_Res34_cifar10_OOD.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

## treat as OOD10
print(np.mean(np.average(cover_accs, 1)))
print(np.std(np.average(cover_accs, 1)))

print(np.mean(np.average(avg_errors, 1)))
print(np.std(np.average(avg_errors, 1)))

0.91779995
0.008299977
0.08770001
0.013800006


In [21]:
with open('cifar10/FCI_VGG16_cifar10_OOD.pkl', 'rb') as inp:
    res = pickle.load(inp)
cover_accs, avg_errors = res

for i in range(len(avg_errors)):
    cover_accs[i] = cover_accs[i].numpy()
    avg_errors[i] = avg_errors[i].numpy()
cover_accs = np.array(cover_accs)
avg_errors = np.array(avg_errors)

## treat as OOD10
print(np.mean(np.mean(cover_accs[1:])))
print(np.mean(np.mean(avg_errors[1:], 0)))

0.85690004
7.6563997
